# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: hackathon
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  pgadmin:
    extends:
      file: ./postgresql.yml
      service: pgadmin
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak

volumes:
    hackathon-postgresql:
    hackathon-pgadmin-data: